// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace IVRRecording.Web.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddExplicitForeignKeyOnRecording : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExplicitForeignKeyOnRecording));
        
        string IMigrationMetadata.Id
        {
            get { return "201510061848414_AddExplicitForeignKeyOnRecording"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
